Convert notebooks to scripts
Urban-Analytics-Technology-Platform/acbm pull request #23
Opened 2024-04-29 14:20 UTC by sgreenbury

This PR closes #21 converting the preprocessing notebooks to scripts so that the downstream data is constructed.

Outstanding areas to look at refining:
- Make deterministic: set seed/random_state as part of input
- Write metrics that capture matching performance/quality to file for validation (relates to #17)
- [Flexible input](https://click.palletsprojects.com/en/8.1.x/) to allow different sized samples upon running the script

2024-04-29 14:22 UTC, sgreenbury commented on scripts/2_match_households_and_individuals.py
> +spc = spc.head(15000)
Perhaps can be an input parameter for the script to determine if run on the whole population?

2024-04-30 15:38 UTC, Hussein-Mahfouz reviewed
Thanks for the readme! Everything else looks good to me, except I can't run the 1_prep_synthpop.py. I think this is an issue in my setup so can revisit it in the weekly meeting. Happy to merge this if @BZ-BowenZhang is ok with it also

2024-05-02 15:51 UTC, BZ-BowenZhang commented on scripts/1_prep_synthpop.py
I got an error here saying `TypeError: Builder.unnest() got an unexpected keyword argument 'rsuffix'`

2024-05-02 16:09 UTC, sgreenbury commented on scripts/1_prep_synthpop.py
I think this might be due to the version of `uatk-spc` in `Poetry.lock` not having this API feature yet. If you run `poetry update` first this might remove the error?

2024-05-02 23:18 UTC, BZ-BowenZhang requested changes

2024-05-02 23:18 UTC, BZ-BowenZhang commented on scripts/2.1_sandbox-match_households.py
The rest of scripts are okay, successfully run after making some simple changes

2024-05-02 23:34 UTC, BZ-BowenZhang commented on scripts/2.1_sandbox-match_households.py
This error seems fixed when I ran `poetry update` again

2024-05-03 11:16 UTC, BZ-BowenZhang approved these changes

2024-05-03 11:24 UTC, merged